Code review
atenaiis/Weather-app pull request #1
Opened 2021-06-02 17:41 UTC by atenaiis

testing linterns

2021-06-07 21:40 UTC, atenaiis commented
Team,

This is my Weather app, please follow the readme file instructions .

cheers!!

2021-06-07 21:58 UTC, umararshadbut reviewed
# Status: INVALID :red_circle: 

**Hi @atenaiis **
The readme is descriptive :clap: your commit messages are perfect :clap: However there is a problem with your git-flow and pull request description. Please do not merge the pull request before approving the project. And add the description in the pull request.
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

2021-06-07 23:48 UTC, atenaiis commented
Team
 this is a weather app to display current information from a specific place. Using JS connected with a third-part API and applying concepts about Promises, Async/Await syntax, and API connection.
Please follow Readme file instructions.

Cheers!

2021-06-08 01:06 UTC, MkrtichSargsyan requested changes
## _Status:_ Changes Requested :recycle:

## Hello Atenais Campos García

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:

## To Highlight :tada:


1. Your readme is descriptive.
2. You have descriptive git commit messages.


Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved

- [x] Make the develop branch default branch

- [ ] remove commented code

- [x] There should be a toggle control to determine if the result will be shown in Celsius or Fahrenheit  [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png)

- [ ] Kindly add  ```"start": "webpack-dev-server --mode development --open" // optional``` to your package.json scripts, or remove ```npm run start``` from your readme instructions

- [ ] There should be error handling for promises or async/await [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png)



## OPTIONAL

- [ ] It would be nice if you add a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API 

- [ ] it would be nice if it fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-06-08 01:07 UTC, MkrtichSargsyan commented on README.md
> +  `npm run start`
There is no ```start``` script in the package.json file

2021-06-08 01:08 UTC, MkrtichSargsyan commented on src/app.js
> +  // icon.setAttribute('src', iconSrc);
Kindly remove the commented code

2021-06-08 01:09 UTC, MkrtichSargsyan commented on src/forecast.js
> +    const response = await fetch(this.weatherURI + query);
Kindly add a try-catch block

2021-06-08 01:10 UTC, MkrtichSargsyan commented on src/forecast.js
> +    const response = await fetch(this.cityURI + query);
Kindly add a try-catch block

2021-06-08 21:33 UTC, NtwaliHeritier approved these changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑**

Hello @atenaiis 
Great work making the requested changes👏👏👏👏

You can merge👏👏

Happy coding 💻💻

2021-07-08 20:58 UTC, merged